version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test
      MYSQL_USER: debbagh
      MYSQL_PASSWORD: 12345678
    ports:
      - "7089:5066"
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8089:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 5066
      PMA_ARBITRARY: 1

volumes:
  db_data: {}